#!/bin/bash

# Default values (optional)
SAVE_POINT=/scratch/$USER/ckpts
TEMP_POINT=/scratch/$USER/temp
SESSION=$(date +"%Y%m%d%H%M%S")
SESSION_POOL=/scratch/.session

# Function to show how to use the script
usage() {
    echo "Usage: $0 -j <job_path> -a <argument> -n <nodes> -p <processes>"
    exit 1
}

# Parse flags
while getopts "j:a:n:p:" opt; do
  case $opt in
    j) USER_INPUT="$OPTARG" ;;
    a) ARGUMENT="$OPTARG" ;;
    n) NODE="$OPTARG" ;;
    p) PROCESS="$OPTARG" ;;
    *) usage ;;
  esac
done

# Check if required variables are empty
if [[ -z "$USER_INPUT" || -z "$ARGUMENT" || -z "$NODE" || -z "$PROCESS" ]]; then
    echo "Error: Missing required arguments."
    usage
fi


PORT=$(dmtcp_coordinator -p 0 --exit-on-last --daemon 2>&1 | awk '/Port:/ {print $2}')

# Directory checks
for dir in "$SAVE_POINT" "$TEMP_POINT" "$SESSION_POOL"; do
    [[ ! -d "$dir" ]] && mkdir -p "$dir"
done

JOB_PATH=$(realpath -m -- "$USER_INPUT" 2>/dev/null)

fileName="$SESSION.temp"
filePath="$TEMP_POINT/$fileName"
touch $filePath

echo "#!/bin/bash" >> $filePath
echo "#SBATCH --job-name=mul_matrix" >> $filePath
echo "#SBATCH --nodes=$NODE" >> $filePath
echo "#SBATCH --ntasks-per-node=$PROCESS" >> $filePath
echo "#SBATCH --output=initial_job_%j.out" >> $filePath
echo "#SBATCH --cpus-per-task=1" >> $filePath
echo "#SBATCH --mem=1024M" >> $filePath
echo "export DMTCP_COORD_HOST=blade-master" >> $filePath
echo "export DMTCP_COORD_PORT=$PORT" >> $filePath

echo "module load mpi/mpich" >> $filePath
echo "export HWLOC_XMLFILE=/scratch/hwxml/canonical.xml" >> $filePath
echo "export HWLOC_THISSYSTEM=1" >> $filePath


echo "srun --mpi=pmi2 dmtcp_launch --coord-host \$DMTCP_COORD_HOST \\" >> $filePath
echo "	--coord-port \$DMTCP_COORD_PORT \\" >> $filePath
echo "	--ckptdir "$SAVE_POINT/$SESSION" \\" >> $filePath
echo "	$JOB_PATH $ARGUMENT" >> $filePath


mkdir -p $SAVE_POINT/$SESSION

mv $filePath "$SAVE_POINT/$SESSION/job.sbatch"

cd "$SAVE_POINT/$SESSION"

jobId=$(sbatch job.sbatch | awk '{print $4}') 
echo "Job was sent successfully job id: $jobId"

touch "$SESSION_POOL/$jobId"
echo "$SESSION $PORT 1" >> "$SESSION_POOL/$jobId"


